import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import Loading from "./loading";
import {Suspense} from "react";
import {ReduxProvider} from "@/redux/ReduxProvider";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <ReduxProvider>
        <Suspense fallback={<Loading/>}>
          {children}
        </Suspense>
      </ReduxProvider>
      </body>
    </html>
  );
}
